### ISSUE TITLE
Submitting a request while the response is collapsed makes it impossible to see the response

### ISSUE THREAD

**Issue by patrickhuy** [AnWeber/httpbook#100]
When submitting a request while the response is collapsed makes it impossible to see the response

Reproduce:
1. Create any request and submit it
2. Collapse the response
3. Send the request again
4. Expand the response
5. -> response is no longer shown, instead an empty space is shown

I'm on MacOS 14.0 on an M1 Mac, VSCode is version 1.83.0. 

https://github.com/AnWeber/httpbook/assets/66731536/a4a26c6b-da15-4766-a4aa-ac98ca8e2bd2

**Comment by AnWeber** [comment]
I would now guess a bug in vscode. I can not control the display. I only provide a NotebookOutput object. The display is then controlled by VSCode. And I could reproduce the same error in another notebook extension. Please create an issue at [microsoft/vscode](https://github.com/microsoft/vscode)
![notebook](https://github.com/AnWeber/httpbook/assets/13434739/678bb308-fb43-40a9-9e70-3acfe01288b4)

**Comment by patrickhuy** [comment]
I created an issue - in the jupyter repository - not sure if the vscode repository may have been better. Will attempt to follow up if someone there tells me that it's in the wrong place.
Intrestingly in Jupyter notebooks it works diffently and the output is shown despite the cell output being collapsed.

**Comment by AnWeber** [comment]
I think the output rendering, uses code from this [folder](https://github.com/microsoft/vscode/tree/17eb59f1467bd9c0cbccf7ac341257b83cf4f6e7/src/vs/workbench/contrib/notebook), but we will see.
