### ISSUE TITLE
Variables do not carry over between cells

### ISSUE THREAD

**Issue by patrickhuy** [AnWeber/httpbook#102]
When working with variables like this

```
{{
  exports.foo = 'bar';
}}
GET https://google.de/?q={{foo}}
###
GET https://google.de/?q={{foo}}
```
The second request will fail with 
```
ReferenceError: foo is not defined
```

For unknown reasons I had it randomly work but most of the time it does not work. In httpyac it works fine.

**Comment by AnWeber** [comment]
That's actually intentional. I separate the regions that these do not share the variables. Exception is when multiple cells are executed at once, then the variable scope is not always reset, but that could be explicitly enabled.
You should use global regions for your case.

```
{{
  exports.foo = 'bar';
}}
###
GET https://google.de/?q={{foo}}
###
GET https://google.de/?q={{foo}}
```

**Comment by patrickhuy** [comment]
Mh, the original use-case is/was to set variables in "post-request" scripts based on the API response with a "m-n" structure. So:

```
# create job using method A
POST /job
{{
  exports.id=1;
}}
###
# create job using method B
POST /job
{{
  exports.id=2;
}}
###
# get job status
GET /job/{{id}}
###
# delete job
DELETE /job/{{id}}
```

the intention is that one of the "create job" methods will be used but the id of either would become available in "get job status". I therefore can not `@ref` the "correct" one.

In the "httpYac" extension this also works fine as is. In "httpBook" it does not. Does `useRegionScopedVariables` not default to false? I also tried setting it to false but it did not change anything. Setting it to true did make this no longer work.

**Comment by AnWeber** [comment]
~~vscode-httpyac and httpbook may differ from each other in detail here. The reason is that each cell is considered as a separate file by vscode and I create a virtual httpFile but I am missing some details like the scoped variable store.~~ ... Ok yeah you got me. I will align both approaches.

**Comment by AnWeber** [comment]
Your example should work with the new version v6.2.3

**Comment by patrickhuy** [comment]
Can confirm, it works nicely! :)

**Comment by AnWeber** [comment]
thx for your feedback.-)
