### ISSUE TITLE
When using "Run all", is the order of execution of cells guaranteed?

### ISSUE THREAD

**Issue by denisrossetre** [AnWeber/httpbook#105]
I'm using httpbook to automate API testing, and I saw in one instance that my tests are flaky when run with the "Run All" toolbar button.

Running them one cell after another works perfectly.

I cleared my history and reopened the request file to debug the order of calls, but now it works again.

My question: is the order of calls guaranteed when using Run All? is the runner waiting for the response of one cell before running the next one?

**Comment by AnWeber** [comment]
Actually, the [call on my part would always be the same](https://github.com/AnWeber/httpbook/blob/main/src/extension/notebook/httpNotebookKernel.ts#L115). But it may be related to the error from #102 or maybe the cells I receive from the notebook are not sorted. Is the error related to missing variables? Do you have a stack or error message for me?

**Comment by denisrossetre** [comment]
I could not reproduce the problem deterministically -- the error was in the test of the business logic.

Basically, I'm setting a boolean to true, testing that it is true, setting it false, testing that it is false, and those tests were randomly failing.

I'm going to test extensively this and report back.

**Comment by denisrossetre** [comment]
Seems to work fine! we can close the issue

**Comment by AnWeber** [comment]
THX fornfeedback
