### ISSUE TITLE
Add possibility to view the sent request

### ISSUE THREAD

**Issue by nidomiro** [AnWeber/httpbook#108]
I would like to view the request that was sent out, e.g. for manual review of variable replacements.

Is there a way to view the request Body / URL / Headers in the form they are sent out (= with replaced placeholders)?

**Comment by AnWeber** [comment]
I would actually have implemented a separate view (NotebookRenderer) for this use case. Either you use this or you use the display in the OutputChannel `httpyac - Request`.

![response](https://github.com/AnWeber/httpbook/assets/13434739/e27d4a35-1cdf-44ee-ac9c-8866c937ca78)
