### ISSUE TITLE
Provide a way to suppress the output of a cell

### ISSUE THREAD

**Issue by Spitfire1900** [AnWeber/httpbook#110]
When making a request to an endpoint that returns a large json dictionary the entire editor is filled with the response body, provide a way to suppress the output of a cell, such that only the first <N> lines is displayed, either through a VSCode setting or as a snippet in the cell body.

**Comment by AnWeber** [comment]
You could alter response with a script. Using `@responseLogging` only affects response used for outpt, using `@response` also changes response used for all purposes

```
GET https://postman-echo.com/get

{{@responseLogging
  response.body = response.body.slice(0,10);
}}
```

In this way, you can create an optimized display afterwards and also create Markdown, for example.
