### ISSUE TITLE
Assertion result shows incorrectly 

### ISSUE THREAD

**Issue by Mirodil** [AnWeber/httpbook#127]
Hello,

The HTTP assertation results show incorrectly, even when tests are passing it shows `0 Passing Tests  2 Failing Tests`
Here is an example:
![image](https://github.com/user-attachments/assets/a34403db-b831-4cbd-a301-7bb5cfe409ba)

is it possible to fix it?

**Comment by AnWeber** [comment]
fixed with v3.2.4. I overlooked a breaking change in httpyac. Sorry
