### ISSUE TITLE
Prevent cell output from editing the .http file

### ISSUE THREAD

**Issue by matthewturner** [AnWeber/httpbook#130]
Another excellent tool!

When running `.dib` files, the output from cells are not recorded in the underlying `.dib` file. When running httpbook `.http`, the output does update the .http file and then shows up in git as a modified file:

![image](https://github.com/user-attachments/assets/fda462c8-7333-4f72-b69e-103c46cc96ee)

This makes it more difficult to manage. Is there any way to suppress this behaviour?

Thanks!

**Comment by AnWeber** [comment]
You could disable setting `httpbook.saveWithOutputs`.

**Comment by matthewturner** [comment]
I knew you'd have it covered! Thanks so much.
