### ISSUE TITLE
How to switch between markdown and HTTP views ?

### ISSUE THREAD

**Issue by Carlos920** [AnWeber/httpbook#132]
Sometimes I want to use HTTP views, but I don't know how to switch between them

**Comment by AnWeber** [comment]
@Carlos920  Do you mean switching presentations?
![switch_presentations](https://github.com/user-attachments/assets/4be895e6-8271-48fb-a52a-688cc7e4d9f3)

**Comment by Carlos920** [comment]
> @Carlos920 Do you mean switching presentations?您的意思是切换演示文稿吗？ ![switch_presentations](https://private-user-images.githubusercontent.com/13434739/376059529-4be895e6-8271-48fb-a52a-688cc7e4d9f3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NjUwODIsIm5iZiI6MTcyODg2NDc4MiwicGF0aCI6Ii8xMzQzNDczOS8zNzYwNTk1MjktNGJlODk1ZTYtODI3MS00OGZiLWE1MmEtNjg4Y2M3ZTRkOWYzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAwMTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMzMxOWFmZTk0YzU4MWIwNDk0MDQ0YmE3NTU3ZGY4OTk1OTc2NGEwNWZmMzA1MmU2M2U3NWQzMzg1NGEyYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UheJVetpUqzA1Qw1aucV-Rs43K8LFU8XMxXaw6qCQKI) [ ![switch_presentations](https://private-user-images.githubusercontent.com/13434739/376059529-4be895e6-8271-48fb-a52a-688cc7e4d9f3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NjUwODIsIm5iZiI6MTcyODg2NDc4MiwicGF0aCI6Ii8xMzQzNDczOS8zNzYwNTk1MjktNGJlODk1ZTYtODI3MS00OGZiLWE1MmEtNjg4Y2M3ZTRkOWYzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAwMTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMzMxOWFmZTk0YzU4MWIwNDk0MDQ0YmE3NTU3ZGY4OTk1OTc2NGEwNWZmMzA1MmU2M2U3NWQzMzg1NGEyYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UheJVetpUqzA1Qw1aucV-Rs43K8LFU8XMxXaw6qCQKI) ](https://private-user-images.githubusercontent.com/13434739/376059529-4be895e6-8271-48fb-a52a-688cc7e4d9f3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NjUwODIsIm5iZiI6MTcyODg2NDc4MiwicGF0aCI6Ii8xMzQzNDczOS8zNzYwNTk1MjktNGJlODk1ZTYtODI3MS00OGZiLWE1MmEtNjg4Y2M3ZTRkOWYzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAwMTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMzMxOWFmZTk0YzU4MWIwNDk0MDQ0YmE3NTU3ZGY4OTk1OTc2NGEwNWZmMzA1MmU2M2U3NWQzMzg1NGEyYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UheJVetpUqzA1Qw1aucV-Rs43K8LFU8XMxXaw6qCQKI) [ ](https://private-user-images.githubusercontent.com/13434739/376059529-4be895e6-8271-48fb-a52a-688cc7e4d9f3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NjUwODIsIm5iZiI6MTcyODg2NDc4MiwicGF0aCI6Ii8xMzQzNDczOS8zNzYwNTk1MjktNGJlODk1ZTYtODI3MS00OGZiLWE1MmEtNjg4Y2M3ZTRkOWYzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAwMTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMzMxOWFmZTk0YzU4MWIwNDk0MDQ0YmE3NTU3ZGY4OTk1OTc2NGEwNWZmMzA1MmU2M2U3NWQzMzg1NGEyYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UheJVetpUqzA1Qw1aucV-Rs43K8LFU8XMxXaw6qCQKI)

It is to switch the editor interface between the interface installed with the httpbook plugin and the interface not installed.
My current operation is to disable the httpbook plugin when switching the editor interface

**Comment by AnWeber** [comment]
You can also switch the editor interface in vscode. Click on the Tab of the file and use `reopen with` 

https://m.youtube.com/watch?v=pOduvfsUngw

**Comment by Carlos920** [comment]
> You can also switch the editor interface in vscode. Click on the Tab of the file and use `reopen with`
> 
> https://m.youtube.com/watch?v=pOduvfsUngw

ok, thanks
