### ISSUE TITLE
bug across OS : Failed to save 'myfile.http': t.getCells is not a function

### ISSUE THREAD

**Issue by commandline-be** [AnWeber/httpbook#134]
whenever a file is save it returns this message

Failed to save 'myfile.http': t.getCells is not a function

**Comment by AnWeber** [comment]
@commandline-be  I need some more information. The error does not occur for me. Neither in vscode nor vscodium. I edited an existing and created a new file from scratch. No Error

**Comment by AnWeber** [comment]
In latest Insiders this bug occurs

**Comment by AnWeber** [comment]
I added a typeguard till vscode team discusses what to do. There is a minor API Change which breaks my code. NotebookData is not always a class but my extension is handed over a object with same interface
