### ISSUE TITLE
Mimetype text/html is not 

### ISSUE THREAD

**Issue by dlucazeau** [AnWeber/httpbook#27]
When I use another notebook (in my case .NET interactive), I have to change the mimetype of the output to the built-in and repeat this over and over:
![image](https://user-images.githubusercontent.com/4538922/125094851-e33bcb00-e0d3-11eb-8852-3ef261f6cada.png)

With the active mimetype I get this output:
![image](https://user-images.githubusercontent.com/4538922/125094948-fb134f00-e0d3-11eb-85be-92877ec7b421.png)

and with built-in I get a more readable output:
![image](https://user-images.githubusercontent.com/4538922/125095004-09616b00-e0d4-11eb-8824-1bf826e4ad1c.png)

It is really boring.

**Comment by AnWeber** [comment]
The behavior is well known. I will implement a workaround in time, but actually it would make more sense if vscode would support setting the default renderer (see Better support when multiple renderers are installed microsoft/vscode#125876).

**Comment by AnWeber** [comment]
I have now added a workaround for the mimetype problem. I no longer use the correct mimetypes, but my own. I'm still waiting to see how the ticket at Microsoft develops and will eventually revert the change.
