### ISSUE TITLE
How not to open systematically th "Ouput Httpyac - log"

### ISSUE THREAD

**Issue by dlucazeau** [AnWeber/httpbook#28]
I don't want to see the output with the logs for each request.

How can I do ?

**Comment by AnWeber** [comment]
The `httpyac.showlogRequestOutput ` [setting](https://github.com/AnWeber/vscode-httpyac/blob/main/src/logger.ts#L43) should prevent it. I will remove the function, but in the next release of vscode-httpyac probably completely, because it is not really user friendly.

**Comment by AnWeber** [comment]
With the latest update of vscode-httpyac (v2.20.0) and httpbook (v1.0.0), the outputchannel is not always brought to the front.
