### ISSUE TITLE
How to set or change environments?

### ISSUE THREAD

**Issue by ramsundark5** [AnWeber/httpbook#30]
In vscode-httpyac, there is an option to choose an environment before execution. Don't see that option when using httpbook.

**Comment by AnWeber** [comment]
It is in the status bar below a cell. In this gif environment dev is selected: https://raw.githubusercontent.com/AnWeber/httpbook/main/images/httpbin.gif

**Comment by ramsundark5** [comment]
Got it. thanks for the quick response!

**Comment by rngtng** [comment]
Had same problem. Confusing part was that the area is just empty and didn't hint one could change the env there. maybe add `env: -` as it's done in the vs-plugin.

**Comment by AnWeber** [comment]
An error has crept in. Initially the environments were either `undefined` or at least filled with one value. Due to changes in httpyac there is now also the state with a empty array. I have overlooked this place while refactoring. It is fixed with the next release

**Comment by AnWeber** [comment]
StatusbarItem is fixed with new v2.2.1

**Comment by rngtng** [comment]
thx
