### ISSUE TITLE
httpbook.saveWithOutputs does not work

### ISSUE THREAD

**Issue by smaktacular** [AnWeber/httpbook#31]
... or does not work as expected? 

When set to false, the contents of the file containing the http requests are changed, also after a window reload/restart of vscode.  
The unsaved file indicator pops up although nothing has been change about the actual requests.

Is there maybe a way to completely redirect the response to the console?

vscode version win64 1.60.1 (system)

**Comment by AnWeber** [comment]
Thank you. I was able to reproduce the behavior after calling a request. Just opening the http file was not enough. In your case, was it enough to open the editor and if so, were only blank lines removed?

If you use vscode-httpyac, then it is possible to use only the output in the output channel (setting `httpyac.responseViewMode`). For the notebook display I have currently not implemented it. 
![image](https://user-images.githubusercontent.com/13434739/134052716-235746a8-3c63-41c5-83c4-a332673484d4.png)

**Comment by smaktacular** [comment]
> Thank you. I was able to reproduce the behavior after calling a request. Just opening the http file was not enough. In your case, was it enough to open the editor and if so, were only blank lines removed?

No, just opening a file did not trigger any changes. Executing a request did. I could not see any blank lines getting removed either...

Offtopic: I really like the projects around httpYac. Thank you for your work!

**Comment by AnWeber** [comment]
I will then provide a new version with the fix in a timely manner. I just want to test the grpc extension in httpyac again and would then update it, 

Thanks for using the extension.

**Comment by AnWeber** [comment]
I have provided the update. Please test it and let me know if it doesn't work as expected. Thank you.
