### ISSUE TITLE
How to configure response output

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpbook#39]
Is there a way to configure the response output similar as in CLI or the std-plugin? For me the full request/response cycle is show, whereas I'd like to see only the response body (at first).

**Comment by AnWeber** [comment]
VSCode should ship with this feature, but I do not know how to use it. See https://code.visualstudio.com/updates/v1_62#_notebooks and https://github.com/microsoft/vscode/issues/125876
That is one reason why I prefer std.plugin.

**Comment by AnWeber** [comment]
And maybe the [MonacoEditor](https://marketplace.visualstudio.com/items?itemName=anweber.httpbook-monacorenderer) (#Ad) is interesting for you. The standard JSON display does not know a find dialog.

**Comment by AnWeber** [comment]
Did you see this dropdown? Select Output Mimetype and you can choose other renderer.
![image](https://user-images.githubusercontent.com/13434739/144124623-a5c2b610-5c30-44ae-b790-d4e5628c13a5.png)

**Comment by rngtng** [comment]
ah I haven't seen this, that's indeed a good start. I only can't select `application/json` there.. need to look in more detail why. thx

**Comment by rngtng** [comment]
nvm mind solved it. I had a test line enabled so mime type was different. I updated setting to output only failed tests, with that it works. nice! closing issue...

**Comment by AnWeber** [comment]
That's all the fun about the Notebook Editor. Here you could also directly integrate [OpenMaps/ Leaflet](https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-leaflet) for example.
