### ISSUE TITLE
Output is always displayed in separate code window, but never als "notebook" inline

### ISSUE THREAD

**Issue by NTTAKR** [AnWeber/httpbook#41]
Hi all, 

I installed httpBook - Rest Client in VsCode but it displays .http files totally different than advertied. 
Output of the request is always shown in a separate window,

How can I configure httpBook to have an interface like in your demo page?

**Comment by AnWeber** [comment]
Hello, how do you execute the request. By using the arrow next to the cell. Or by command?
![httpbook](https://user-images.githubusercontent.com/13434739/145630081-9c997754-b32a-4122-a80c-1b30e5e1314e.gif)

I would imagine that you started the request by command. `httpBook` is again an addition for `vscode-httpyac` (Notebook Editor API was/is not stable yet). The command is provided by `vscode-httpyac` and there the way to open the response is standard.

Was it like that?

**Comment by NTTAKR** [comment]
Hi Andreas,

The problem was that I did not get the view like the one you posted below.
But I had to close and open the file to get it to show like a “notebook”.

Now all problems are solved.

Thanks for your quick response and for the awesome extension. I really like the visual appeal it has and the functionality is also awesome.

Mit freundlichen Grüßen / Best regards,
  Andreas Kroll

**Comment by AnWeber** [comment]
Freut mich, dass dir die Erweiterung gefällt. Viel Spaß damit,

Freundliche Grüße,
Andreas Weber
