### ISSUE TITLE
impossible execution of a cell

### ISSUE THREAD

**Issue by dlucazeau** [AnWeber/httpbook#47]
Hi
With the last update of yesterday the execution arrow is no longer displayed.
I reinstalled the previous version from .vsix, and the arrow is there.
![2022-03-07_16-07-13](https://user-images.githubusercontent.com/4538922/157060764-16030746-79b9-4b95-b35a-b4647052117a.png)

Regards

**Comment by AnWeber** [comment]
Thanks for the tip. I was relying too much on Typescript validation, but it is currently not working as expected. I have fixed the error with v3.0.2.

**Comment by dlucazeau** [comment]
It's perfect, thank you.
 :thumbsup:
