### ISSUE TITLE
Markdown rendered as plain text

### ISSUE THREAD

**Issue by andriichumak** [AnWeber/httpbook#54]
Most of the time markdown is not applied to the `.http` file's comments.

Steps to reproduce:
1. Create a new `.http` file, open it with VSCode with httpbook plugin.
2. Add there some markdown section, save.
3. Close the file and open it again.

**Result**: The markdown section is not formatted, i.e. rendered as plain text.
**Expected result**: Markdown should be converted to formatted text.

It's curios that if I enter the edit mode, change something in the section and "apply" changes for the section, it would render proper formatting. Sometimes formatting would also appear when I add a new section before the one in question.

VSCode: 1.67.1 
httpbook: 3.1.0

**Comment by AnWeber** [comment]
I accidentally used the mimetype instead of the required languageId. I don't understand why it still worked during the implementation. But there the interface was still proposed api. With the next version of httpbook the error is fixed.

**Comment by andriichumak** [comment]
Thanks, @AnWeber !

**Comment by AnWeber** [comment]
v3.1.1 published. thx
