### ISSUE TITLE
Do not output the result of @ref or @forceRef request

### ISSUE THREAD

**Issue by dlucazeau** [AnWeber/httpbook#63]
Hello
When you use @ref or @forceRef to get for example a token with a login, it's a shame to have the output of this intermediate request. It makes it more difficult to read the result of the request we are really interested in.

I believe that this was not always the case.

**Comment by AnWeber** [comment]
@dlucazeau Yes I have added the behavior afterwards. But unfortunately I didn't notice that this doesn't behave so nice in httpbook. I mainly use vscode-httpyac where the previous requests are simply closed again. I'll try to improve it again in a timely manner.

**Comment by AnWeber** [comment]
By default, the responses are now no longer output. However, it can be enabled by setting `httpbook.outputAllRespones`. This is released with version 3.1.2
