### ISSUE TITLE
View size of request

### ISSUE THREAD

**Issue by sebastienroul** [AnWeber/httpbook#68]
!Feature

It would be great to be able to limit the height size of the request view.
Cause when request has long body, then the window is very height, and the reponse is very far (need to scroll a lot)

![image](https://user-images.githubusercontent.com/2582255/185779300-73f6d907-77a6-42fc-9932-798cc8235bf0.png)

Suggested presentation
![image](https://user-images.githubusercontent.com/2582255/185779440-dff6feb8-8a14-45a8-bf24-1ef5cb1d9081.png)

Thanks

**Comment by AnWeber** [comment]
VSCode does not provide an API on how I can limit the size of the [code/markdown cell](https://code.visualstudio.com/api/references/vscode-api#NotebookCellData). This is only possible for the output. Workaround would be to collapse the body or dump it to a separate JSON file ([example](https://httpyac.github.io/guide/request.html#imported-request-body)).
If this is not enough create an issue in [microsoft/vscode](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Anotebook+is%3Aopen). I could not find one with this request and I would support it. This is one reason I mainly use vscode-httpyac with the editor view. The response is open besides the request and is always visible.
