### ISSUE TITLE
Code Formatting and Assist

### ISSUE THREAD

**Issue by st11x** [AnWeber/httpbook#73]
Hi,

Is it possible to apply formatting to the Httpbook? I have a lot of JSON in the book and I have to copy them out to reformat, then paste them back. It would be great if it is available directly. 

Also, is it possible to enable code assist in the script blocks?

Thanks
  Matt

**Comment by AnWeber** [comment]
httpbook has the same limitation as vscode-httpyac. The extension is just an add-on to the other extension that implements the VSCode Notebook Api. This was originally only available in VSCode Insider and I wanted to play with it. For the reason as noted in the discussion, I would start with implementing the [LSP](https://github.com/AnWeber/vscode-httpyac/issues/101) first. After that, I would trace the features as in vetur, and then these points would be possible. But to have time for this is really my problem.
