### ISSUE TITLE
Httpbook formatting broken by saving in VScode 1.76.1

### ISSUE THREAD

**Issue by sibbowulf** [AnWeber/httpbook#82]
Hi,

After upgrading to VScode 1.76 (code_1.76.1-1678294265_amd64.deb) on Ubuntu 22.04 LTS  my httpyac files in httpbook format gets broken when loaded into VScode.  The requests get truncated in httpbook whereas disabling the httpbook extension and using only httpyac in VScode works normally.

httpyac looks like this:
###

GET http://{my_url}}/my/api/v1
/config

in httpbook this is truncated to:
 my_url}}/my/api/v1
/config

Maybe some control code change in VScode with undesired side effects ?

**Comment by AnWeber** [comment]
<img width="288" alt="image" src="https://user-images.githubusercontent.com/13434739/226003703-8f10353b-1ac6-4753-be7d-efe0e2885bd2.png">
same. I will take a look.  I thought at first that I accidentally broke the api to `vscode-httpyac`. But seems at first sight not so.

**Comment by sibbowulf** [comment]
Thank you.

Verified as working in my environment also. 
Thank you for the quick fix.
