### ISSUE TITLE
How can I make use of httpyac-plugin-jq in Notebook?

### ISSUE THREAD

**Issue by holgerh** [AnWeber/httpbook#84]
I have the Plugin "httpyac-plugin-jq" installed in the repository. 
When I execute the request with the extension httpyac-vscode, the plugin is executed. 
When I execute the request with httpbook, the plugin is not executed.

How can I execute the notebook and get the result from the plugin?

**Comment by AnWeber** [comment]
I think I have an idea. VSCode uses Virtual Documents for the display of notebooks. These use an alternative filename, which does not match the real file Uri. Maybe a file URI conversion is missing.

**Comment by AnWeber** [comment]
Seems to be no easy fix. Workaround is to add some script block

```
# @name example
# @jq .slideshow.slides | map({title})
GET https://httpbin.org/json

{{+responseLogging
  delete response.parsedBody
}}
```

**Comment by AnWeber** [comment]
I have now solved it by means of a proxy that ensures that all bodies are always correctly deleted when the body is changed. fixed with release of vscode-httpyac
