### ISSUE TITLE
websocket run infinitely even server is dead

### ISSUE THREAD

**Issue by exitNA** [AnWeber/httpbook#96]
hello:
I start a ws request, but it has an error response, but doesn't stop.
![image](https://github.com/AnWeber/httpbook/assets/5160007/9d4d28e6-b78b-40e7-aa1b-07c0f42ec8e6)

**Comment by AnWeber** [comment]
I did not take into account that an error can occur during the connection setup and the connection is closed directly. In this case the Promise was not resolved. With the next version of vscode-httpyac it is also corrected in httpbook.
